# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bondrewd Programming Language
email: admin@bondrewd.dev
description: >-
  A programming language focusing on compile-time flexibility and runtime performance
baseurl: ""
url: "https://bondrewd.dev"
github_username: abel1502

github_url: https://github.com/abel1502/bondrewd
docs_url: https://bondrewd.readthedocs.io/

# TODO: dfn?
shukufuku_translation: <abbr title='&#x795D;&#x798F;, jap. "Blessing"'>Shukufuku</abbr>


plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-liquify
  - jekyll-pages-directory

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:categories/:year-:month-:day-:title"  # :output_ext
      subheader: "Blog"
      subheader_link: "/blog"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - README.md
  - CNAME
  - "*.yml"
  - "*.config.js"
  - "*.bak"
  - .gitignore
  - .vscode
  - .github
  - .git
  - package*.json
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
